name: torch
channels:
  - pytorch
  - nvidia
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _tflow_select=2.3.0=mkl
  - abseil-cpp=20220623.0=h8cdb687_6
  - absl-py=1.4.0=py310h06a4308_0
  - aiohttp=3.9.3=py310h5eee18b_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - alsa-lib=1.2.8=h166bdaf_0
  - arrow-cpp=11.0.0=ha770c72_5_cpu
  - asttokens=2.4.1=pyhd8ed1ab_0
  - astunparse=1.6.3=py_0
  - async-timeout=4.0.3=py310h06a4308_0
  - attr=2.5.1=h166bdaf_1
  - aws-c-auth=0.6.24=h84a1944_5
  - aws-c-cal=0.5.20=hc60faf5_6
  - aws-c-common=0.8.11=h0b41bf4_0
  - aws-c-compression=0.2.16=h034cb4b_3
  - aws-c-event-stream=0.2.18=h75388cd_6
  - aws-c-http=0.7.4=hf084cc8_2
  - aws-c-io=0.13.17=h10df833_2
  - aws-c-mqtt=0.8.6=hc41645a_6
  - aws-c-s3=0.2.4=h1b8f470_3
  - aws-c-sdkutils=0.1.7=h034cb4b_3
  - aws-checksums=0.1.14=h034cb4b_3
  - aws-crt-cpp=0.19.7=h0073717_7
  - aws-sdk-cpp=1.10.57=h4707e7a_4
  - bedtools=2.31.1=hf5e1c6e_2
  - biopython=1.78=py310h7f8727e_0
  - blas=1.0=mkl
  - blinker=1.6.2=py310h06a4308_0
  - bottleneck=1.3.7=py310ha9d4c09_0
  - brotli=1.0.9=h5eee18b_7
  - brotli-bin=1.0.9=h5eee18b_7
  - brotli-python=1.0.9=py310h6a678d5_7
  - bzip2=1.0.8=h5eee18b_5
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - cachetools=4.2.2=pyhd3eb1b0_0
  - certifi=2025.8.3=pyhd8ed1ab_0
  - cffi=1.16.0=py310h5eee18b_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.2.2=pyhd8ed1ab_0
  - contourpy=1.2.0=py310hdb19cb5_0
  - cryptography=42.0.5=py310hdda0065_1
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.4.99=0
  - cuda-runtime=12.1.0=0
  - cuda-version=11.8=hcce14f8_3
  - cudatoolkit=11.8.0=h6a678d5_0
  - cudnn=8.9.2.26=cuda11_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h52b45da_1
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.6.7=py310h6a678d5_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - et_xmlfile=1.1.0=py310h06a4308_0
  - exceptiongroup=1.2.0=pyhd8ed1ab_2
  - expat=2.5.0=h6a678d5_0
  - ffmpeg=4.3=hf484d3e_0
  - fftw=3.3.10=nompi_hf0379b8_106
  - filelock=3.13.1=py310h06a4308_0
  - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
  - font-ttf-inconsolata=2.001=hcb22688_0
  - font-ttf-source-code-pro=2.030=hd3eb1b0_0
  - font-ttf-ubuntu=0.83=h8b1ccd4_0
  - fontconfig=2.14.1=h4c34cd2_2
  - fonts-anaconda=1=h8fa9717_0
  - fonts-conda-ecosystem=1=hd3eb1b0_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.12.1=h4a9f257_0
  - frozenlist=1.4.0=py310h5eee18b_0
  - gast=0.4.0=pyhd3eb1b0_0
  - gettext=0.22.5=h59595ed_2
  - gettext-tools=0.22.5=h59595ed_2
  - gflags=2.2.2=h5888daf_1005
  - giflib=5.2.1=h5eee18b_3
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - glog=0.6.0=h6f12383_0
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py310heeb90bb_0
  - gnutls=3.6.15=he1e5248_0
  - google-pasta=0.2.0=pyhd3eb1b0_0
  - grpc-cpp=1.51.1=h27aab58_1
  - gst-plugins-base=1.21.3=h4243ec0_1
  - gstreamer=1.21.3=h25f0c4b_1
  - gstreamer-orc=0.4.38=hd590300_0
  - hdf5=1.12.1=h2b7332f_3
  - icu=70.1=h27087fc_0
  - idna=3.4=py310h06a4308_0
  - importlib-metadata=7.1.0=pyha770c72_0
  - importlib_metadata=7.1.0=hd8ed1ab_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - ipykernel=6.29.3=pyhd33586a_0
  - jack=1.9.22=h11f4161_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.3=py310h06a4308_0
  - jpeg=9e=h5eee18b_1
  - jupyter_client=8.6.1=pyhd8ed1ab_0
  - jupyter_core=5.7.2=py310hff52083_0
  - keras-preprocessing=1.1.2=pyhd3eb1b0_0
  - kiwisolver=1.4.4=py310h6a678d5_0
  - krb5=1.20.1=h143b758_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libabseil=20220623.0=cxx17_h05df665_6
  - libarrow=11.0.0=h2ebd325_5_cpu
  - libasprintf=0.22.5=h661eb56_2
  - libasprintf-devel=0.22.5=h661eb56_2
  - libbrotlicommon=1.0.9=h5eee18b_7
  - libbrotlidec=1.0.9=h5eee18b_7
  - libbrotlienc=1.0.9=h5eee18b_7
  - libcap=2.66=ha37c62d_0
  - libclang13=15.0.7=default_h5d6823c_5
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.9.0.20=0
  - libcups=2.3.3=h36d4200_3
  - libcurand=10.3.5.119=0
  - libcurl=8.7.1=h251f7ec_0
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libdb=6.2.32=h6a678d5_1
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.10=h28343ad_4
  - libffi=3.4.4=h6a678d5_0
  - libflac=1.4.3=h59595ed_0
  - libgcc=15.1.0=h767d61c_4
  - libgcc-ng=15.1.0=h69a702a_4
  - libgcrypt=1.10.3=hd590300_0
  - libgettextpo=0.22.5=h59595ed_2
  - libgettextpo-devel=0.22.5=h59595ed_2
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libglib=2.78.4=hdc74915_0
  - libgomp=15.1.0=h767d61c_4
  - libgoogle-cloud=2.7.0=h21dfe5b_1
  - libgpg-error=1.49=h4f305b6_0
  - libgrpc=1.51.1=h4fad500_1
  - libiconv=1.17=hd590300_2
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libllvm14=14.0.6=hdb19cb5_3
  - libllvm15=15.0.7=hadd5161_1
  - libnghttp2=1.57.0=h2d74bed_0
  - libnpp=12.0.2.50=0
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libogg=1.3.5=h27cfd23_1
  - libopus=1.3.1=h7b6447c_0
  - libpng=1.6.39=h5eee18b_0
  - libpq=15.2=hb675445_0
  - libprotobuf=3.21.12=hfc55251_2
  - libsndfile=1.2.2=hc60ed4a_1
  - libsodium=1.0.18=h36c2ea0_1
  - libsqlite=3.45.3=h2797004_0
  - libssh2=1.11.0=h251f7ec_0
  - libstdcxx=15.1.0=h8f9b012_4
  - libstdcxx-ng=13.2.0=h7e041cc_5
  - libsystemd0=252=h2a991cd_0
  - libtasn1=4.19.0=h5eee18b_0
  - libthrift=0.18.0=h5e4af38_0
  - libtiff=4.5.1=h6a678d5_0
  - libtool=2.4.7=h27087fc_0
  - libudev1=253=h0b41bf4_0
  - libunistring=0.9.10=h27cfd23_0
  - libutf8proc=2.8.0=hf23e847_1
  - libuuid=1.41.5=h5eee18b_0
  - libvorbis=1.3.7=h7b6447c_0
  - libwebp-base=1.3.2=h5eee18b_0
  - libxcb=1.13=h1bed415_1
  - libxkbcommon=1.5.0=h79f4944_1
  - libxml2=2.10.3=hca2bb57_4
  - libzlib=1.2.13=hd590300_5
  - lightning-utilities=0.11.2=pyhd8ed1ab_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_0
  - markdown=3.4.1=py310h06a4308_0
  - markupsafe=2.1.3=py310h5eee18b_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py310h5eee18b_1
  - mkl_fft=1.3.8=py310h5eee18b_0
  - mkl_random=1.2.4=py310hdb19cb5_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpg123=1.32.6=h59595ed_0
  - mpmath=1.3.0=py310h06a4308_0
  - multidict=6.0.4=py310h5eee18b_0
  - munkres=1.1.4=py_0
  - mysql=5.7.24=h721c034_2
  - mysql-common=8.0.32=ha901b37_0
  - mysql-libs=8.0.32=hd7da12d_0
  - nccl=2.21.5.1=h6103f9b_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - nettle=3.7.3=hbbd107a_1
  - nspr=4.35=h6a678d5_0
  - nss=3.89.1=h6a678d5_0
  - numexpr=2.8.7=py310h85018f9_0
  - numpy=1.26.4=py310h5f9d8c6_0
  - numpy-base=1.26.4=py310hb5e798b_0
  - oauthlib=3.2.2=py310h06a4308_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=3.1.8=h7b32b05_0
  - opt_einsum=3.3.0=pyhd3eb1b0_1
  - orc=1.8.2=hfdbbad2_2
  - parquet-cpp=1.5.1=2
  - parso=0.8.3=pyhd8ed1ab_0
  - pcre2=10.42=hebb0a14_0
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pillow=10.2.0=py310h5eee18b_0
  - platformdirs=4.2.0=pyhd8ed1ab_0
  - ply=3.11=py310h06a4308_0
  - prompt-toolkit=3.0.42=pyha770c72_0
  - psutil=5.9.8=py310h2372a71_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pulseaudio=16.1=ha8d29e2_1
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pyarrow=11.0.0=py310h633f555_5_cpu
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pyasn1-modules=0.2.8=py_0
  - pybigwig=0.3.22=py310h79000e5_2
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.17.2=pyhd8ed1ab_0
  - pyjwt=2.4.0=py310h06a4308_0
  - pyopenssl=24.0.0=py310h06a4308_0
  - pyparsing=3.0.9=py310h06a4308_0
  - pyqt=5.15.10=py310h6a678d5_0
  - pyqt5-sip=12.13.0=py310h5eee18b_0
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.14=h955ad1f_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python_abi=3.10=2_cp310
  - pytorch=2.2.2=py3.10_cuda12.1_cudnn8.9.2_0
  - pytorch-cuda=12.1=ha16c6d3_5
  - pytorch-lightning=2.2.1=pyhd8ed1ab_0
  - pytorch-mutex=1.0=cuda
  - pytz=2023.3.post1=py310h06a4308_0
  - pyzmq=25.1.2=py310h6a678d5_0
  - qt-main=5.15.6=hf6cd601_5
  - re2=2023.02.01=hcb278e6_0
  - readline=8.2=h5eee18b_0
  - requests-oauthlib=1.3.0=py_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - s2n=1.3.37=h3358134_0
  - setuptools=68.2.2=py310h06a4308_0
  - sip=6.7.12=py310h6a678d5_0
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.1.10=h6a678d5_1
  - sqlite=3.41.2=h5eee18b_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - sympy=1.12=py310h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - tensorboard-plugin-wit=1.8.1=py310h06a4308_0
  - termcolor=2.1.0=py310h06a4308_0
  - tk=8.6.12=h1ccaba5_0
  - tomli=2.0.1=py310h06a4308_0
  - torchaudio=2.2.2=py310_cu121
  - torchmetrics=1.3.2=pyhd8ed1ab_0
  - torchtriton=2.2.0=py310
  - torchvision=0.17.2=py310_cu121
  - tornado=6.3.3=py310h5eee18b_0
  - traitlets=5.14.2=pyhd8ed1ab_0
  - tzdata=2024a=h04d1e81_0
  - urllib3=2.1.0=py310h06a4308_1
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - werkzeug=2.3.8=py310h06a4308_0
  - wheel=0.41.2=py310h06a4308_0
  - wrapt=1.14.1=py310h5eee18b_0
  - xcb-util=0.4.0=h516909a_0
  - xcb-util-image=0.4.0=h166bdaf_0
  - xcb-util-keysyms=0.4.0=h516909a_0
  - xcb-util-renderutil=0.3.9=h166bdaf_0
  - xcb-util-wm=0.4.1=h516909a_0
  - xkeyboard-config=2.38=h0b41bf4_0
  - xz=5.4.6=h5eee18b_0
  - yaml=0.2.5=h7b6447c_0
  - yarl=1.9.3=py310h5eee18b_0
  - zeromq=4.3.5=h6a678d5_0
  - zlib=1.2.13=hd590300_5
  - zstd=1.5.5=hc292b87_0
  - pip:
      - accelerate==0.28.0
      - alphagenome==0.2.0
      - anndata==0.10.8
      - anyio==4.4.0
      - appdirs==1.4.4
      - argcomplete==3.2.3
      - argh==0.31.2
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - array-api-compat==1.7.1
      - arrow==1.3.0
      - arviz==0.21.0
      - async-lru==2.0.4
      - attrs==25.3.0
      - babel==2.15.0
      - backcall==0.2.0
      - baskerville==0.1.dev272+gaf9e2df
      - beartype==0.18.0
      - beautifulsoup4==4.12.3
      - binaryornot==0.4.4
      - bioservices==1.12.1
      - bleach==6.1.0
      - blessed==1.20.0
      - borzoi==1.0.1.dev5+g77670d9
      - borzoi-pytorch==0.4.1
      - boto3==1.38.1
      - botocore==1.38.1
      - cattrs==24.1.3
      - chardet==5.2.0
      - click==8.1.8
      - cloudml-hypertune==0.1.0.dev6
      - cmake==4.0.0
      - colorlog==6.9.0
      - cookiecutter==2.6.0
      - croniter==1.3.15
      - dateutils==0.6.12
      - deepdiff==7.0.1
      - defusedxml==0.7.1
      - deprecation==2.1.0
      - diffusers==0.27.2
      - discrete-key-value-bottleneck-pytorch==0.1.1
      - dmslogo==0.6.2
      - docopt==0.6.2
      - docstring-parser==0.16
      - easydev==0.13.3
      - editdistance==0.8.1
      - editor==1.6.6
      - einops==0.7.0
      - einx==0.1.3
      - enformer-pytorch==0.8.10
      - executing==2.2.0
      - fastapi==0.88.0
      - fastjsonschema==2.20.0
      - fastkde==2.1.3
      - flatbuffers==25.2.10
      - fqdn==1.5.1
      - frozendict==2.4.1
      - fsspec==2023.12.2
      - future==1.0.0
      - gcsfs==2023.12.2.post1
      - gevent==25.4.1
      - gffutils==0.12
      - google-api-core==2.24.2
      - google-auth==2.39.0
      - google-auth-oauthlib==1.2.2
      - google-cloud-aiplatform==1.90.0
      - google-cloud-bigquery==3.31.0
      - google-cloud-core==2.4.3
      - google-cloud-resource-manager==1.14.2
      - google-cloud-storage==2.0.0
      - google-crc32c==1.7.1
      - google-resumable-media==2.7.2
      - googleapis-common-protos==1.70.0
      - gpytorch==1.14
      - greenlet==3.2.1
      - grequests==0.7.0
      - grpc-google-iam-v1==0.14.2
      - grpcio==1.72.0rc1
      - grpcio-status==1.72.0rc1
      - h11==0.14.0
      - h5netcdf==1.6.1
      - h5py==3.10.0
      - httpcore==1.0.5
      - httpx==0.27.0
      - huggingface-hub==0.22.2
      - hydra-slayer==0.5.0
      - icecream==2.1.4
      - imageio==2.37.0
      - imageio-ffmpeg==0.4.4
      - immutabledict==4.2.1
      - inquirer==3.4.0
      - intervaltree==3.1.0
      - ipython==8.12.3
      - ipywidgets==8.1.3
      - isoduration==20.11.0
      - itsdangerous==2.2.0
      - jaxtyping==0.3.2
      - jmespath==1.0.1
      - joblib==1.4.2
      - json5==0.9.25
      - jsonargparse==4.43.0
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - jupyter==1.0.0
      - jupyter-console==6.6.3
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.2
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.2.3
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.2
      - jupyterlab-widgets==3.0.11
      - keopscore==2.3
      - keras==2.15.0
      - kipoi==0.8.6
      - kipoi-conda==0.3.1
      - kipoi-utils==0.7.7
      - kipoiseq==0.7.1
      - lazy-loader==0.4
      - legacy-api-wrap==1.4
      - libclang==18.1.1
      - lightning==1.9.5
      - lightning-cloud==0.5.70
      - line-profiler==4.2.0
      - linear-operator==0.6
      - llvmlite==0.44.0
      - logomaker==0.8
      - lxml==5.4.0
      - markdown-it-py==3.0.0
      - matplotlib==3.10.1
      - mdurl==0.1.2
      - mistune==3.0.2
      - mizani==0.11.4
      - ml-dtypes==0.3.2
      - natsort==7.1.1
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - ncls==0.0.68
      - networkx==3.4.2
      - nose==1.3.7
      - notebook==7.2.1
      - notebook-shim==0.2.4
      - numba==0.61.2
      - nvidia-cublas-cu12==12.2.5.6
      - nvidia-cuda-cupti-cu12==12.2.142
      - nvidia-cuda-nvcc-cu12==12.2.140
      - nvidia-cuda-nvrtc-cu12==12.2.140
      - nvidia-cuda-runtime-cu12==12.2.140
      - nvidia-cudnn-cu12==8.9.4.25
      - nvidia-cufft-cu12==11.0.8.103
      - nvidia-curand-cu12==10.3.3.141
      - nvidia-cusolver-cu12==11.5.2.141
      - nvidia-cusparse-cu12==12.1.2.141
      - nvidia-nccl-cu12==2.16.5
      - nvidia-nvjitlink-cu12==12.2.140
      - openpyxl==3.1.2
      - ordered-set==4.1.0
      - overrides==7.7.0
      - packaging==24.2
      - palettable==3.3.0
      - pandas==2.2.3
      - pandocfilters==1.5.1
      - patsy==0.5.6
      - pip==25.2
      - pipreqs==0.5.0
      - plotnine==0.13.6
      - polars==0.20.18
      - polygraph==0.0.post1.dev39+g3cf32ef
      - prometheus-client==0.20.0
      - proto-plus==1.26.1
      - protobuf==6.32.0
      - pybedtools==0.10.0
      - pybind11==2.13.6
      - pydantic==1.10.21
      - pyfaidx==0.7.2.2
      - pykeops==2.3
      - pyliftover==0.4.1
      - pymemesuite==0.1.0a3
      - pynndescent==0.5.13
      - pyranges==0.0.129
      - pyro-api==0.1.2
      - pyro-ppl==1.9.1
      - pysam==0.22.1
      - python-json-logger==2.0.7
      - python-multipart==0.0.20
      - python-slugify==8.0.4
      - pyyaml==6.0.2
      - qnorm==0.8.1
      - qtconsole==5.5.2
      - qtpy==2.4.1
      - readchar==4.2.1
      - referencing==0.35.1
      - regex==2023.12.25
      - related==0.7.3
      - requests==2.32.3
      - requests-cache==1.2.1
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.7.1
      - rich-click==1.8.8
      - rotary-embedding-torch==0.5.3
      - rpds-py==0.19.0
      - ruamel-yaml==0.18.10
      - ruamel-yaml-clib==0.2.12
      - runs==1.2.2
      - s3transfer==0.12.0
      - safetensors==0.4.2
      - scanpy==1.11.1
      - scikit-image==0.25.2
      - scikit-learn==1.5.2
      - scikit-posthocs==0.9.0
      - scipy==1.15.2
      - seaborn==0.13.2
      - send2trash==1.8.3
      - session-info==1.0.0
      - session-info2==0.1.2
      - shapely==2.1.0
      - simplejson==3.19.2
      - sniffio==1.3.1
      - sorted-nearest==0.0.39
      - sortedcontainers==2.4.0
      - soupsieve==2.5
      - starlette==0.22.0
      - starsessions==1.3.0
      - statsmodels==0.13.5
      - stdlib-list==0.10.0
      - suds-community==1.2.0
      - tabulate==0.8.10
      - tangermeme==0.2.1
      - tensorboard==2.15.2
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.2.2
      - tensorflow==2.15.1
      - tensorflow-estimator==2.15.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - tensorly==0.8.1
      - tensorly-torch==0.4.0
      - terminado==0.18.1
      - text-unidecode==1.3
      - threadpoolctl==3.5.0
      - tifffile==2025.2.18
      - tinycss2==1.3.0
      - tinydb==4.8.0
      - tokenizers==0.15.2
      - torchinfo==1.8.0
      - torchsummary==1.5.1
      - tqdm==4.65.2
      - transformers==4.39.3
      - typeguard==4.4.4
      - types-python-dateutil==2.9.0.20240316
      - typing-extensions==4.14.1
      - umap-learn==0.5.6
      - uri-template==1.3.0
      - url-normalize==2.2.0
      - uvicorn==0.34.2
      - vector-quantize-pytorch==1.14.6
      - wadler-lindig==0.1.5
      - webcolors==24.6.0
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - websockets==11.0.3
      - widgetsnbextension==4.0.11
      - wordcloud==1.9.4
      - xarray==2025.1.2
      - xarray-einstats==0.8.0
      - xlrd==2.0.1
      - xmltodict==0.14.2
      - xmod==1.8.1
      - yarg==0.1.9
      - zipp==3.18.1
      - zope-event==5.0
      - zope-interface==7.2
      - zstandard==0.24.0
prefix: /home/hxcai/anaconda3/envs/torch
